### ISSUE TITLE
Environment variables do not currently work

### ISSUE THREAD

**Issue by ehmicky** [cball/netlify-plugin-contextual-env#2]
This Build plugin does not completely work due to a missing feature in Netlify Build tracked [here](https://github.com/netlify/build/issues/1129): `process.env` is not currently shared between Build plugins and `build.command`.

However the `.env` file logic is not impacted by this.

**Comment by cball** [comment]
Thanks @ehmicky! For background, I started down the road of just setting `process.env` and only added the `.env` file step after I discovered exactly what you outlined in netlify/build#1129.

If we can just set `process.env` I don't think we need to write an `.env` file at all.

Perhaps for now we take out the piece where we set `process.env` and continue to have users add the build step. Then it can be simplified if netlify/build#1129 lands.
